#Errors
PERSON_ERROR = "PERSON_NOT_FOUND"
COMMAND_ERROR = "COMMAND_NOT_FOUND"
NULLPOINTER_ERROR = "NONE"
INFORMATION_ERROR = "Inadequate Information"
CHILD_ERROR = "CHILD_ADDITION_FAILED"

#Sucess
CHILD_ADDITION_SUCCESS = "CHILD_ADDITION_SUCCEEDED"
#Gender
MALE = "M"
FEMALE = "F"

#Commands
SIBLINGS = "Siblings"
PATERNAL_UNCLE = "Paternal-Uncle"
PATERNAL_AUNT = "Paternal-Aunt"
MATERNAL_AUNT = "Maternal-Aunt"
MATERNAL_UNCLE = "Maternal-Uncle"
SISTER_IN_LAW = "Sister-In-Law"
BROTHER_IN_LAW = "Brother-In-Law"
COMMAND_SON = "Son"
COMMAND_DAUGHTER = "Daughter"